language: c

sudo: false

cache:
  directories:
    - $HOME/travis-cache

os:
  - linux

compiler:
  - clang

addons:
  apt:
    packages:
    - language-pack-is
    - git-svn
    - apache2

matrix:
  include:
    - env: jobname=StaticAnalysis
      os: linux
      compiler:
      addons:
      services:
        - docker
      before_install:
      before_script:
      script: ci/run-static-analysis.sh
      after_failure:

script: echo "aa"

notifications:
  email: false
